version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Darko123!
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  web:
    image: fastapi-app
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:Darko123!@db:5432/postgres
