name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo "${{ secrets.darko1234 }}" | docker login -u "${{ secrets.darkopavikevik12 }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.darkopavikevik12 }}/fastapi-app:latest .
          docker push ${{ secrets.darkopavikevik12 }}/fastapi-app:latest
